### ISSUE TITLE
Varying lasershot repetition rates

### ISSUE THREAD

**Issue by Ropzn** [PollyNET/Pollynet_Processing_Chain#106]
Concerning v3.0  Preprocess functions

[https://github.com/PollyNET/Pollynet_Processing_Chain/blob/v3.0/lib/pre-process/pollyPreprocess.m](url)

Maybe I don't understand it right. 
Is the strategy right now, that we a assume the laser repetition rate to be constant (beeing our reference clock) and accordingly brute force reset the timestamps, as soon as it's not 600 shots/30sec ?

If so, than that should be the other way around, or ?

I would guess the time stamp is the reference clock and sometimes some more or fewer shots occur.
Maybe ask Ronny for clarification.

Moreover the function uses a fixed number of 600, which probably stands for 20shots/sec in 30 sec.
However the new diode-pumped systems work on 100shots/sec.
So this number somehow should be replaced by a variable.

`   %% Re-sample the temporal grid to 30 s, if it's not in 30s.    
    nInt = round(600 / nanmean(data.mShots(1, :), 2));  
    % number of profiles to be
    % integrated. Usually, 600
    % shots per 30 s`

**Comment by ZPYin** [comment]
Thanks for reporting this issue. I will handle it in the next few days.

**Comment by HolgerPollyNet** [comment]
@Ropzn is this solution ok for you?
