### ISSUE TITLE
near range SNR in att bsc files

### ISSUE THREAD

**Issue by griesche** [PollyNET/Pollynet_Processing_Chain#124]
It would be great to save also the near-range SNR in the netCDF att bsc files. So far, only the far-range SNR is stored in these files.

**Comment by HolgerPollyNet** [comment]
Could this be a job for @ulysses78  ?

**Comment by ulysses78** [comment]
I can do that. Should be no problem (I guess). Is this the same SNR-variable which is altready stored  in the "normal" att_bsc-files? Only for 355 and 532 nm?
Do you also want to store the quality-mask-variable (355+532nm)?

**Comment by griesche** [comment]
What do you mean by 'normal att_bsc_files'? I also already started on this, but if you're faster you can also do the job :)

Yes, only 355 and 532 nm. I think the quality mask would be good as well.

**Comment by ulysses78** [comment]
By 'normal att_bsc_files' I mean the att_bsc files of the far range, where those variables are already implemented.

**Comment by ZPYin** [comment]
So far, the near-range `SNR` is calculated inside `Picasso`, but was not saved in the netCDF file. 
You can extract the near-range `SNR` from `data.SNR` (3D dataset: channel x height x time), and implement the **saving** within `pollySaveNRAttnBeta.m`, similar to what was done in `pollySaveAttnBeta.m` for far-range variables.

**Comment by griesche** [comment]
I have updated the pollySaveNRAttnBeta.m so that the near-range SNR is also stored. I also started with the quality mask, but this is not yet in the data input to pollySaveNRAttnBeta.m. 

I have opened a pull request to the dev branch,

**Comment by ulysses78** [comment]
Can this issue be closed?

**Comment by griesche** [comment]
Yes I think so.
