### ISSUE TITLE
quasi angström image not produced

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#134]
The image of the temporal development of the qausi angström exponent is not created and no entry is written to the done filelist.

See as one example here:

https://polly.tropos.de/datavis/location/13/6/?dates=[2017-04-18T00:00:00,2017-04-19T00:00:00]

I guess this is a bug related to the development of Picasso v3.0?

**Comment by ZPYin** [comment]
Bug Description
---------------

No plots of quasi-angstroem exponent after moving to Picasso v3.x.

Bug Analysis
------------

Wrong implementation of channel existence check for 1064 total.

``` matlab
flag1064 = data.flagFarRangeChannel & data.flag1064nmChannel & data.flagCrossChannel;   % before
```

Bug Fixes
---------

Fix channel existence check, as below:

``` matlab
flag1064 = data.flagFarRangeChannel & data.flag1064nmChannel & data.flagTotalChannel;
```

> Picasso version was updated to `v3.3`.
