### ISSUE TITLE
Near-real time processing of quasi-products corrupted

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#135]
During the operational processing, it seems that the latest quasi products are empty, and the target categorization is false, while the input,- the att. bsc's and volume depol-  is ok!

For example:
![grafik](https://user-images.githubusercontent.com/55800803/148541323-c3b2c608-74fc-48f5-b3c4-50dcbb6b2265.png)
![grafik](https://user-images.githubusercontent.com/55800803/148541446-ea1d0342-2e8d-43a5-a265-53f4c4fa9853.png)

![grafik](https://user-images.githubusercontent.com/55800803/148541387-1c5693d4-b28d-45cc-92cf-d3932708384b.png)
![grafik](https://user-images.githubusercontent.com/55800803/148541412-762390ee-651b-4c01-8f6f-6a9d6362e6da.png)
![grafik](https://user-images.githubusercontent.com/55800803/148541485-50f1b417-7791-4504-be00-6b0fe146e5ee.png)

Any idea what could be the problem? Is it due to the transfer of data within the chain?

**Comment by ZPYin** [comment]
It's not a bug with Picasso, but something wrong with the latest GDAS1 profiles. Below is the GDAS1 profile for leipzig:

![image](https://user-images.githubusercontent.com/7610928/148633724-49e75737-7bd2-478e-8b27-ad3941f2ae41.png)

I don't know why the temperature (TEMP) and height (HGTS) are both zeros. Anyhow, this will feed in invalid meteorological data without triggering any warnings from Picasso. Therefore, all products associated with Rayleigh scattering properties will be wrong, to name a few, particle backscatter, quasi-backscatter/depol. 

I enahnced the check for meteorological data to filter such invalid gdas1 profiles (see commit https://github.com/PollyNET/Pollynet_Processing_Chain/commit/3f02c5b7d62cfb62ee74eadd0b16c82b7bd33c57). But maybe someone still needs to dive into the GDAS1 profile issue.

**Comment by HolgerPollyNet** [comment]
Many thanks! I will inform our GDAS folks! Best

**Comment by HolgerPollyNet** [comment]
Hi @ZPYin ,

since you enhanced your check for invalid GDAS files, only standard atmosphere data is used even though the GDAS profiles are available. Can you check?

**Comment by ZPYin** [comment]
> Hi @ZPYin ,
> 
> since you enhanced your check for invalid GDAS files, only standard atmosphere data is used even though the GDAS profiles are available. Can you check?

My last implementation was incorrect. The condition check that I used to resolve the original issue, leads to this new bug. The details in terms of the bug and the following-up fix can be found in commit  https://github.com/PollyNET/Pollynet_Processing_Chain/commit/c8af058fa867c887f9e4d649b616363eed01d9df.

Ps, 
Fixing issues or bugs can get tricky as the increasing of the project volume.

**Comment by HolgerPollyNet** [comment]
Many thanks @ZPYin , I really appreciate the efforts you are still doing for us. In future we will of course try to more and more fix the bugs by ourselves. But your advise is always welcome, as it might be much easier for you to get an idea were the bug us located!
