### ISSUE TITLE
Bug in Raman retrievals?

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#143]
Hi all,

since some time, I am wondering about some "strange" Raman backscatter retrievals at day time. At the beginning I thought this is due to background noise, but while trying to "optimize" the setting for the reference height search, I realized that I cannot reproduce the profiles.

Here is what Picasso gives for one nice example from  Mindelo on 23 July at around 9:21 to 09:46 UTC:
As you see the profiles are way to high. The reference height is 6.9 to 8.9 km and the reference value is 5e-8. **But as you see, the whole profile does not reach this value at all in this height range.** 

![2021_07_23_Fri_CPV_09_20_32_0921_0946_Bsc_Raman](https://user-images.githubusercontent.com/55800803/157425964-cd2a15e2-33a3-49cf-be35-384becb218af.png)

I calculated the same profile with my own, old program and here is how it looks like there:
![cabi23072021](https://user-images.githubusercontent.com/55800803/157427117-46b08f5c-9341-4d72-87cd-071c9938d634.png)
I know the profiles are far from perfect, but it is the same settings as used in Picasso, and the results are quite different.

Do you have any idea where to look at? My personal feeling is, that it might be related to the transmission correction...

**Comment by ZPYin** [comment]
Yes, it's a bug associated with negative signal filtering. I've fixed it in a new commit (to `dev` branch). Below are the details regarding this bug.

## Bug Description

Wrong (Raman) backscatter retrieval, where clear positive bias can be seen for 355 and 532 nm. (see the comment above)

## Bug Analysis

Negative signals were filtered when calculating the summed signal at the reference height range, both for Raman and Elastic signal. 
https://github.com/PollyNET/Pollynet_Processing_Chain/blob/be0e33589fc9aa9f32d71efd3bf506c49899d4e2/lib/retrievals/pollyRamanBsc.m#L170-L177

While Raman signal is usually weaker than Elastic signal; thus this signal filtering will make Raman go towards more positive bias. This will finally contribute to positive bias for the backscatter. In addition, when the signal gets noiser (**at daytime**), more negative values will be wiped out, Then you see much larger positive bias... 

## Bug Fixes

Remove the negative signal filter... (Actually I have done that for 1064, but forget to repeat it for 355 and 532... OK! my bad...)

Now the profile looks like more consistent with the Labview results (see below).

![image](https://user-images.githubusercontent.com/7610928/157999856-5c84bdd0-ea7d-4b67-9ada-42307226f846.png)

**Comment by HolgerPollyNet** [comment]
Great! Thanks for your work! Your expert knowledge is indispensable :-). Let us check the operational data for 2-3 days and then we can close the issue!

Best
Holger
