### ISSUE TITLE
Restructuring the visualization of long-term  calibration results

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#168]
Currently, the calibration results (Lidar constant, depo, water vapor) are calculated, stored in a DB and finally plotted in one plot.

This plot is very, very helpful to check the system behavioiur, however with more and more parameter it gets overloaded.

In my opinion, the meanwhile very heavy loaded https://github.com/PollyNET/Pollynet_Processing_Chain/blob/8a0c6e9d156cf99abf3984992abd179a26a64b22/lib/visualization/pollyxt_ift_displayLTLCali.py needs to be restructured.

In my opinion, two plots wopuld be the best. 
One for lidar constants: 355, 355_NF, 532, 532_NF, 1064.....and one for depol and water vapor constant would be good for a more clear visibilty and future developments.

**Comment by ulysses78** [comment]
I started to seperate the plots. As an example I took the measurements from pollyxt_cpv.
Please have a look and tell me what you think...

![pollyxt_cpv_20220629_long_term_cali_results](https://user-images.githubusercontent.com/86650998/178476623-0f3e6422-4c93-49c8-9484-0b32800099d4.png)

![pollyxt_cpv_20220629_long_term_cali_wv_depol_results](https://user-images.githubusercontent.com/86650998/178476646-398ccf54-46e6-45f9-8ba1-8d50a8ded39f.png)

**Comment by HolgerPollyNet** [comment]
@ulysses78 can be closed, correct?
