### ISSUE TITLE
bugfixing on dev-branch of commit "Enhancement: update sqlite driver"

### ISSUE THREAD

**Issue by ulysses78** [PollyNET/Pollynet_Processing_Chain#174]
We recently recognized that our processing chain stops working when using the dev-branch at its actual commit position (https://github.com/PollyNET/Pollynet_Processing_Chain/commit/11f3046161f229c95dae14cb78ede7540475e72c). We haven't pulled the dev-branch for a while to our rsd2-server. To find out at which committing point the proc-chain crashes, I have tested step by step the latest commits. I found out, that before commit https://github.com/PollyNET/Pollynet_Processing_Chain/commit/173df4e294e319abf1636b5263668ea18e24b04b picasso is working fine. That's way I think there has to be some kind of bug in this commit ("Enhancement: update sqlite driver").

The error message we get is the following:

#### picasso bug report...
```
[2022-10-04 14:40:10] Start water vapor calibration
No IWV measurement for AERONET at 2022-10-04, Evora.
Warning: Java exception occurred:
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no
such table: wv_calibration_constant)
        at org.sqlite.core.DB.newSQLException(DB.java:941)
        at org.sqlite.core.DB.newSQLException(DB.java:953)
        at org.sqlite.core.DB.throwex(DB.java:918)
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:134)
        at org.sqlite.core.DB.prepare(DB.java:257)
        at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:73)
> In loadWVConst at 137
  In selectWVConst at 101
  In picassoProcV3 at 3073
  In picassoProcTodolist at 62
Undefined function or variable "rs".

Error in loadWVConst (line 141)
rs.close;

Error in selectWVConst (line 101)
    [preWVCaliConst, preWVCaliConstStd, ~, ~, caliInstrument] = ...

Error in picassoProcV3 (line 3073)
[wvconstUsed, wvconstUsedStd, data.wvconstUsedInfo] = selectWVConst(...

Error in picassoProcTodolist (line 62)
    reportTmp = picassoProcV3(pollyDataFile, pollyDataTasks.pollyType{iTask},

```

@HolgerPollyNet also thinks this can have seomthing to do with your SQL database update.

I think the best way to fix this, is to make a new commit after the actual one (https://github.com/PollyNET/Pollynet_Processing_Chain/commit/11f3046161f229c95dae14cb78ede7540475e72c).
And remember, we are still using MATLAB 2014 on rsd2 - maybe this could be some starting point for debugging?

**Comment by ZPYin** [comment]
Thanks for your report and your feedback for debugging (really helps me). 

Please see my fix above. I have tested it with pollyxt-cge data (no water vapor channel) under MATLAB 2014a and it works OK. So I will close this issue.
