### ISSUE TITLE
Alternativ to sym toolbox

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#190]
Hey @ZPYin, do you see an alternative for the sym toolbox? with the current matlab (2022a) it is needed for reading the temperature correction function from the config file.

**Comment by ZPYin** [comment]
Please see this commit, and check the commit message for details.

https://github.com/PollyNET/Pollynet_Processing_Chain/commit/6eb9a9e440209ce676abb868dbd553c83ee52229

**Comment by HolgerPollyNet** [comment]
Thanks, is working fine!
