### ISSUE TITLE
Implement 1-step Poliphon

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#196]
input: depol and backscatter at 532 nm, output dust-only bsc., dust fraction....

including plotting and storing in netcdf.

**Comment by Moritz-TROPOS** [comment]
There is already code available for the 1- & 2- step Poliphon method in my BERTHA program.

**Comment by AthenaAugousta** [comment]
Yes, I am planning to use that code as the basis

**Comment by AthenaAugousta** [comment]
Yes, I am planning to use this code as basis

**Comment by elmarinou** [comment]
Athina, I have functions also for every step in python. if you haven't implement this yet, let me know to send you my functions and have a check also ( in addition to Moritz basis). We can also have a meeting on this to show you how my code is structures.
