### ISSUE TITLE
corrupted time in netcdf --> chain stops

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#202]
In case of power failures etc. it can happen that the netcdf is kind of corrupted in the last entry:
![grafik](https://user-images.githubusercontent.com/55800803/221779426-259f59a8-d3e4-4aea-afac-427c5ef831ee.png)
In the example here, the time values are completely nonsense. But currently the processing chain is aborting while plotting the long-term cali. Is there a way to avoid the stopping of the chain but to give a warning?

**Comment by HolgerPollyNet** [comment]
2023-02-28 00:14:56] --> start diplaying lidar housekeeping data.
{Error using timelabellayout (line 166)
The span is too large.

Error in pollyxt_displayHousekeeping (line 21)
[xtick, xtickstr] = timelabellayout(data.mTime, 'HH:MM');

Error in pollyDisplayHousekeeping (line 19)
    pollyxt_displayHousekeeping(data);


Error in picassoProcV3 (line 4844)
    pollyDisplayHousekeeping(data);

Error in picassoProcTodolist (line 62)
    reportTmp = picassoProcV3(pollyDataFile, pollyDataTasks.pollyType{iTask},

**Comment by ZPYin** [comment]
To correct it a little bit... The error happens in the plotting routine of housekeeping data, while it detects an unreasonably large time interval between the first and the last profile. 

To keep processing chain running without collapse, we can can a `try..catch...` in `pollyxt_displayHousekeeping.m`. which I will implement in the next commit. 

But this seems not perfect for this situation. What about inserting another condition check in the preprocessing module, to rule out profiles with strange timestamp (let's say negative values...)?

**Comment by HolgerPollyNet** [comment]
I completely agree. Try and catch can be used as workaround, but more sustainable is the preproc solution!

**Comment by ZPYin** [comment]
see below vol. depol. for PollyXT_CPV with wrong timestamp

![2023_02_26_Sun_CPV_18_00_31_VDR_532](https://user-images.githubusercontent.com/7610928/221822127-57744d30-4b24-4c5d-9bef-72ad32478ab5.png)

**Comment by HolgerPollyNet** [comment]
@ulysses78 can you pull the new version to the server?

**Comment by ulysses78** [comment]
job done!

**Comment by ulysses78** [comment]
this one can be closed, right?
