### ISSUE TITLE
open netcdf

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#238]
I recently get always this warning:
![grafik](https://github.com/PollyNET/Pollynet_Processing_Chain/assets/55800803/8c59a597-7021-4ca6-8902-d033ad888ac0)

Any idea to find out where it comes from?

**Comment by HolgerPollyNet** [comment]
@AthenaAugousta @cristoferjimenez in your recent development, did you close all netcdfs?

**Comment by AthenaAugousta** [comment]
@HolgerPollyNet Yes, I have closed the netcdf. However, in _pollySavePOLIPHON.m_ I just noticed that there are two _end_ statements at the very end. One should be deleted.

**Comment by HolgerPollyNet** [comment]
@cristoferjimenez 
What about you, any potential netcdf not closed?

**Comment by HolgerPollyNet** [comment]
I think this issue has been solved, thus I will close it!
