### ISSUE TITLE
save storage

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#26]
Make config entries for each product to decide wether the product is saved or not--> our server is running slowly out of storage....and some product may not be saved routinously but only on purpose.

**Comment by ZPYin** [comment]
Keyword of `prodSaveList` in polly config file can be used for the control of which products can be saved.

See below:
https://github.com/PollyNET/Pollynet_Processing_Chain/blob/da41163d60d78c45da290842c4ebbdc133dacb9d/config/pollyConfigs/polly_global_config.json#L217
