### ISSUE TITLE
eps/pdf

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#28]
allow option to store output in pdf/eps if desired. may be needed for papers.

**Comment by ZPYin** [comment]
keyword of 'imgFormat' in polly config file can be used to control the image format.

See below:
https://github.com/PollyNET/Pollynet_Processing_Chain/blob/da41163d60d78c45da290842c4ebbdc133dacb9d/config/pollyConfigs/polly_global_config.json#L216
