### ISSUE TITLE
overlap correction of no UV NR available

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#52]
In the current program, it is always assumed that NR is available at both UV and VIs, but this is not the case for PollyXT_DWD. At the moment this is solved, by not saving the overlap function. Thus, this sub function need to be revised.

Furthermore I realized that overlap correctionmode=0 (no correction) should be implemneted.

**Comment by ZPYin** [comment]
Thanks for reporting this.

The fixes about the issues listed above have been implemented. See
- [remove the saving of UV overlap](https://github.com/PollyNET/Pollynet_Processing_Chain/commit/1873285060929dd13175c17b1ba324f6a0b182d4)
- [enable overlapCorMode=0](https://github.com/PollyNET/Pollynet_Processing_Chain/commit/a5181fd9b3bc45d6897ec78671a1857ffd66dd54)
