### ISSUE TITLE
depol calibration based on fixed time

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#68]
needed for old polly versions:

include in the config something like
depol_cali_mode
1=by stored angle (as now)
2= fixed times

then I would introduce 4 more parameter:
depol_cal_time_fixed_p_start: [41460, 54060, 79260]
depol_cal_time_fixed_p_end: [41640, 54240, 79440]
depol_cal_time_fixed_m_start: [41760, 54360, 79560]
depol_cal_time_fixed_m_end: [41940, 54540, 79740]

**Comment by ZPYin** [comment]
Solved.

See commit: 87235f0d8b5d8f02bdde5a5fb70c86f9ebe5ad9b
