### ISSUE TITLE
introduce old labview color scale 

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#73]
as option

**Comment by ZPYin** [comment]
Do you have the colormap in RGB?

**Comment by ZPYin** [comment]
**Labview** style colormap was implemented (see the example below).

**Range-corrected signal**
![2014_01_03_Friday_18_00_15_RCS_FR_532](https://user-images.githubusercontent.com/7610928/96238808-788cb180-0fd1-11eb-8256-b75d605fc63b.png)

**volume depolarization ratio**
![2014_01_03_Friday_18_00_15_VDR_532](https://user-images.githubusercontent.com/7610928/96238861-880bfa80-0fd1-11eb-9211-5c5f10447fc8.png)

The `labview` style colormap can be configured by setting `colormap_basic: "labview"` in the polly config file.

**Comment by HolgerPollyNet** [comment]
WOW, you are so cool!!!!!
    
    Thanks!
    Am 16.10.2020 um 11:04 schrieb ZPYin:
    
    
      
      Labview style colormap was implemented (see
        the example below).
      Range-corrected signal
        
      volume depolarization ratio
        
      The labview style colormap can be configured by
        setting colormap_basic: "labview" in the polly
        config file.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/PollyNET/Pollynet_Processing_Chain/issues/73#issuecomment-709923858",
"url": "https://github.com/PollyNET/Pollynet_Processing_Chain/issues/73#issuecomment-709923858",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    
    -- 
*****************************************************
 Dr. Holger Baars (Dipl.-Met.)
 Leibniz Institute for Tropospheric Research (TROPOS)
 Permoserstr. 15
 04318 Leipzig, Germany
 phone: ++49 341 2717 7314
 fax: ++49 341 2717 99 7314
 email: baars@tropos.de
 internet: http://www.tropos.de
 ****************************************************
