### ISSUE TITLE
Change low color in labview color scale

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#76]
The color outside the given range seems to be white in both cases, below the color scale and above the color scale. This leads to the effect that no sinal is shown as white the same color as for clouds: 
![grafik](https://user-images.githubusercontent.com/55800803/97267988-74f7f680-182b-11eb-980d-ce306b56bfa1.png)
I propose to use black as low color, i.e. in the example everything below 0 and white as high color, i.e. everything above 1.

**Comment by ZPYin** [comment]
The colormap of `labview` has be adjusted. 

PS:

The figure for attenuated backscatter is generated with addtional smoothing in horizontal and vertical. And mask of low SNR was also implemented. The low-SNR bits will be colorized by the color for bad bits, which is defined as below:

https://github.com/PollyNET/Pollynet_Processing_Chain/blob/b0b749a478b1a723ffc1ec24165d216feaea9eb7/lib/python_colormap.py#L582

**Comment by ZPYin** [comment]
**Before** (white for overflow and bad bits):
![2014_01_03_Friday_18_00_15_ATT_BETA_1064](https://user-images.githubusercontent.com/7610928/97271162-31bd7800-186b-11eb-838e-a4bcb87429bd.png)


**After** (white for overflow and black for bad bits):
![2014_01_03_Friday_18_00_15_ATT_BETA_1064](https://user-images.githubusercontent.com/7610928/97270801-b360d600-186a-11eb-9f44-c32e22da03f2.png)
