### ISSUE TITLE
Save attenuated backscatter near-range

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#86]
I think you just need to Copy and modigy the pollyxt_save_att_bsc.m and the insert two lines in the main function-

**Comment by HolgerPollyNet** [comment]
Annett is needed this for comperisons with near-ground in-situ obervations and SAEMS, if @Ronny-TROPOS has no time we should implement this during the 3.0 development. @ZPYin @HolgerPollyNet

**Comment by ZPYin** [comment]
No problem.

I will put this feature in task after I come up with a solution to further control the netCDF files size.

**Comment by ZPYin** [comment]
The near-range attenuated backscatter can be save by adding `aerAttBetaNR` in `prodSaveList`. See example below:

```json
"prodSaveList": ["aerAttBetaNR"]
```
