### ISSUE TITLE
Include possibilty to set reference heigth manually, for a dedicated offline analysis

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#87]
to add this possibility in the config file...., to allow to FORCE retrievals for a given height....

**Comment by ZPYin** [comment]
A new keyword of `flagUseManualRefH` has been added to enable this feature. It was turned off by default (see below). 
https://github.com/PollyNET/Pollynet_Processing_Chain/blob/59b2f52611a69657be1ab380bb21d53dd86c2729/lib/config/polly_global_config.json#L12

The reference heights can be configured by setting `refH_FR_355`, `refH_FR_532` and `refH_FR_1064`, respectively (see below).
https://github.com/PollyNET/Pollynet_Processing_Chain/blob/59b2f52611a69657be1ab380bb21d53dd86c2729/lib/config/polly_global_config.json#L113-L115

For example, **refH_FR_532: [10000, 11000]** stands for manual reference height of 10,000-11,000 (m) for 355 nm.
