### ISSUE TITLE
Show most important paramter in plots

### ISSUE THREAD

**Issue by HolgerPollyNet** [PollyNET/Pollynet_Processing_Chain#98]
I would propose that the most important paramters for a retrieval are stored in the plots shown on polly.tropos.de.

This are:

- water vapor calibration constant used for wv products
- reference height for backscatters
- lidar constants for att. backscatters.
-  (depol calibration constant)

**Comment by ZPYin** [comment]
> I would propose that the most important paramters for a retrieval are stored in the plots shown on polly.tropos.de.
> 
> This are:
> 
> * water vapor calibration constant used for wv products

Done!

![image](https://user-images.githubusercontent.com/7610928/124438615-018b8900-ddab-11eb-9009-54a744afb5f2.png)

> * reference height for backscatters

Done!
![image](https://user-images.githubusercontent.com/7610928/124438856-49aaab80-ddab-11eb-9ca7-d5726cf4621f.png)

> * lidar constants for att. backscatters.

Done!
![image](https://user-images.githubusercontent.com/7610928/124438687-1a943a00-ddab-11eb-856d-8c735184bbc9.png)

> * (depol calibration constant)

Done!
![image](https://user-images.githubusercontent.com/7610928/124438750-2c75dd00-ddab-11eb-814e-b36e857af2d2.png)
